### PR TITLE
Improved file monitoring, added DS and local admin support

### PR DESCRIPTION
**Pull request by schadom**
- Improved input source
- Added support for deployment servers
- Added support for forwarder local admin config

### CODE REVIEW

**Comment by AustinCloudGuru** [comment]
Thanks for the PR.  Please update the code so linting passes and the rest of the checks can be run.

**Comment by AustinCloudGuru** [comment]
Maybe something like this
```
- name: Copy user seeds file
  template:
    src: user-seed.conf.j2
    dest: /opt/splunkforwarder/etc/system/local/user-seed.conf
    mode: 0664
    backup: true
  when: splunk_forwarder_admin_user is defined and splunk_forwarder_admin_pass is defined
  tags: config_copy

- name: Copy deploymentclient file
  template:
    src: deploymentclient.conf.j2
    dest: /opt/splunkforwarder/etc/system/local/deploymentclient.conf
    mode: 0664
    backup: true
  when: splunk_forwarder_depl_server is defined
  tags: config_copy
```

**Comment by schadom** [comment]
> Maybe something like this
> 
> ```
> - name: Copy user seeds file
>   template:
>     src: user-seed.conf.j2
>     dest: /opt/splunkforwarder/etc/system/local/user-seed.conf
>     mode: 0664
>     backup: true
>   when: splunk_forwarder_admin_user is defined and splunk_forwarder_admin_pass is defined
>   tags: config_copy
> 
> - name: Copy deploymentclient file
>   template:
>     src: deploymentclient.conf.j2
>     dest: /opt/splunkforwarder/etc/system/local/deploymentclient.conf
>     mode: 0664
>     backup: true
>   when: splunk_forwarder_depl_server is defined
>   tags: config_copy
> ```

thanks @AustinCloudGuru ... let's see if it works out now :)

**Comment by AustinCloudGuru** [comment]
I'm about to run it again, but it will fail again.  When it does, hold off on making any changes (I think everything is fine, now the tests are broken).  The issue is going to be around the log file ACL change you made.  Since the files don't exist, the tests will fail. I'm adding a bit that will add the files before the test is run.

**Comment by AustinCloudGuru** [comment]
Could you add a file called molecule/default/prepare.yml and add the following:
```
---
- name: Prepare instance for role execution
  hosts: all
  become: true
  tasks:
    - name: Create Nginx Directory
      file:
        path: /var/log/nginx
        state: directory
        owner: root
        group: sys
        mode: 0775
    - name: Create Files
      file:
        path: /var/log/nginx/access.log
        state: touch
        owner: root
        group: sys
        mode: 0775
    - name: Create Files
      file:
        path: /var/log/nginx/error.log
        state: touch
        owner: root
        group: sys
        mode: 0775
```

**Comment by AustinCloudGuru** [comment]
> Could you add a file called molecule/default/prepare.yml and add the following:
> 
> ```
> ---
> - name: Prepare instance for role execution
>   hosts: all
>   become: true
>   tasks:
>     - name: Create Nginx Directory
>       file:
>         path: /var/log/nginx
>         state: directory
>         owner: root
>         group: sys
>         mode: 0775
>     - name: Create Files
>       file:
>         path: {{ item }}
>         state: touch
>         owner: root
>         group: sys
>         mode: 0775
>         with_Items:
>           - /var/log/nginx/access.log
>           - /var/log/nginx/error.log
> ```

nevermind, I pushed it :)

**Pull request merged**
